"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requirePlatformAdmin } from "@/lib/auth";

const PATH = "/locations";

function back(params: Record<string, string>): never {
  const q = new URLSearchParams(params);
  redirect(`${PATH}?${q.toString()}`);
}

function refresh() {
  revalidatePath(PATH);
  revalidatePath("/routes");
}

function str(formData: FormData, key: string): string {
  const v = formData.get(key);
  return typeof v === "string" ? v.trim() : "";
}

function orderOr(formData: FormData, key: string): number | undefined {
  const raw = str(formData, key);
  if (raw === "") return undefined;
  const n = Number(raw);
  return Number.isFinite(n) ? Math.trunc(n) : undefined;
}

function coord(formData: FormData, key: string, min: number, max: number): number | null {
  const raw = str(formData, key);
  if (raw === "") return null;
  const n = Number(raw);
  if (!Number.isFinite(n) || n < min || n > max) back({ error: `${key === "latitude" ? "Latitude" : "Longitude"} must be a number between ${min} and ${max}` });
  return n;
}

/** The same normalisation the database uses for duplicate detection. */
const normalize = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "");

function explain(message: string): string {
  if (message.includes("locations_normalized_name_uniq")) return "A location with this name already exists.";
  if (message.includes("locations_coords_pair")) return "Enter both latitude and longitude, or leave both empty.";
  if (message.includes("permanent")) return "A location code is permanent and cannot be changed.";
  return message;
}

/** Refuses a name that already exists and points the admin at the existing record instead. */
async function assertNew(supabase: Awaited<ReturnType<typeof requirePlatformAdmin>>["supabase"], name: string) {
  const { data } = await supabase.from("locations").select("name, location_code").eq("normalized_name", normalize(name)).maybeSingle();
  if (data) back({ error: `${data.name} (${data.location_code}) already exists. Tick Main route / Pickup & Drop on that location instead of adding a duplicate.` });
}

/** Locations are only ever created here, once, in the single locations table. The code is generated by the database. */
export async function createLocation(formData: FormData) {
  const { supabase } = await requirePlatformAdmin();
  const name = str(formData, "name").replace(/\s+/g, " ").toUpperCase();
  if (!name) back({ error: "A location name is required" });
  await assertNew(supabase, name);

  // "Pickup & Drop" is one switch: it enables the location for both.
  const points = formData.get("is_points_enabled") === "on";
  const row = {
    name,
    state: "Andaman and Nicobar Islands",
    latitude: coord(formData, "latitude", -90, 90),
    longitude: coord(formData, "longitude", -180, 180),
    is_main_route_enabled: formData.get("is_main_route_enabled") === "on",
    is_pickup_enabled: points,
    is_drop_enabled: points,
  };
  const { data, error } = await supabase.from("locations").insert(row).select("name, location_code").single();
  if (error) back({ error: explain(error.message) });
  refresh();
  back({ notice: `${data.name} added with code ${data.location_code}.` });
}

/** Saves one row: name, coordinates, the two assignment checkboxes, status and (when shown) the list orders. */
export async function saveRow(id: string, formData: FormData) {
  const { supabase } = await requirePlatformAdmin();
  const name = str(formData, "name").replace(/\s+/g, " ").toUpperCase();
  if (!name) back({ error: "A location name is required" });
  const points = formData.get("is_points_enabled") === "on";
  const patch: Record<string, unknown> = {
    name,
    latitude: coord(formData, "latitude", -90, 90),
    longitude: coord(formData, "longitude", -180, 180),
    is_main_route_enabled: formData.get("is_main_route_enabled") === "on",
    is_pickup_enabled: points,
    is_drop_enabled: points,
    is_active: formData.get("is_active") === "on",
  };
  const mainOrder = orderOr(formData, "main_route_order");
  if (mainOrder !== undefined) patch.main_route_order = mainOrder;
  const pointsOrder = orderOr(formData, "points_order");
  if (pointsOrder !== undefined) {
    patch.pickup_order = pointsOrder;
    patch.drop_order = pointsOrder;
  }
  const { error } = await supabase.from("locations").update(patch).eq("id", id);
  if (error) back({ error: explain(error.message) });
  refresh();
  back({ notice: `${name} saved.` });
}

/** Disable / enable the whole location. Existing routes and bookings keep working; it is only hidden from new use. */
export async function setLocationActive(id: string, active: boolean) {
  const { supabase } = await requirePlatformAdmin();
  const { error } = await supabase.from("locations").update({ is_active: active }).eq("id", id);
  if (error) back({ error: explain(error.message) });
  refresh();
  back({ notice: active ? "Location enabled." : "Location disabled. Existing routes and bookings are unchanged." });
}
