select cron.unschedule('mark-stale-gps-devices');
select cron.unschedule('purge-location-observations');
drop function if exists public.submit_passenger_location(uuid, numeric, numeric, numeric);
drop function if exists public.revoke_passenger_location_consent(uuid);
drop function if exists public.grant_passenger_location_consent(uuid);
drop function if exists public.ingest_tracker_location(text, text, numeric, numeric, timestamptz, numeric, numeric, numeric);
drop function if exists public.admin_list_gps_integration_events(uuid, int);
drop function if exists public.admin_list_gps_devices();
drop function if exists public.admin_set_bus_driver_fallback(uuid, boolean);
drop function if exists public.admin_set_gps_device_state(uuid, text);
drop function if exists public.admin_unassign_gps_device(uuid);
drop function if exists public.admin_assign_gps_device(uuid, uuid);
drop function if exists public.admin_save_gps_device(uuid, jsonb);
drop function if exists public.operator_disconnect_gps_device(uuid);
drop function if exists public.operator_update_gps_device(uuid, text, text, text, text, text);
drop function if exists public.operator_register_gps_device(uuid, text, text, text, text, text, text);
drop function if exists public.get_bus_gps_status(uuid);
drop function if exists public.get_trip_tracking(uuid);
drop policy if exists trip_track_broadcast_listen on realtime.messages;
-- update_bus_location: re-run the original from 20260924000200_bus_live_tracking.sql after dropping the 4-argument version
drop function if exists public.update_bus_location(uuid, numeric, numeric, numeric);
drop function if exists private.mark_stale_gps_devices();
drop function if exists private.purge_location_observations();
drop function if exists private.refresh_trip_location(uuid);
drop function if exists private.compute_tracking(uuid);
drop function if exists private.passenger_estimate(uuid);
drop function if exists private.dist_to_route_m(uuid, numeric, numeric);
drop function if exists private.dist_to_segment_m(numeric, numeric, numeric, numeric, numeric, numeric);
alter table public.bus_trips drop column if exists location_confidence, drop column if exists location_status, drop column if exists location_source;
alter table public.buses drop column if exists allow_driver_fallback;
drop table if exists public.passenger_location_consent;
drop table if exists public.vehicle_location_observations;
drop table if exists public.gps_integration_events;
drop table if exists public.bus_gps_assignments;
drop table if exists public.gps_devices;
drop function if exists public.admin_set_platform_setting(text, jsonb);
drop function if exists private.setting_bool(text, boolean);
drop function if exists private.setting_num(text, numeric);
drop table if exists public.platform_settings;
